<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "js_faq"
 *
 * Auto generated by Extension Builder 2016-04-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FAQ - Frequently Asked Questions',
	'description' => ' FAQ - Frequently Asked Questions',
	'category' => 'fe',
	'author' => 'Jainish Senjaliya',
	'author_email' => 'jainishsenjaliya@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '5.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0 - 8.0.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);